title: QL 101
tagline: A brand new course on Learning Lab
description: A gentle introduction to QL.
template:
  repo: ql-101-template
  name: ql-101
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
